export const {
	container,
	CharacterPanel,
	AvatarStyles,
	Outline,
	statsContainer,
	statSquares,
	statBox,
	nameBox,
	ranking
} =
{
	container: {
		margin: 'auto',
		marginTop: '3vh',
		width: "76.7vw",
		height: "75vh",
		borderRadius: "16px",
		border: "1px solid #499CE9",
		background: "#171312",
		display: 'flex',
		flexDirection: 'row',
	},
	CharacterPanel: {
		width: "25vw",
		height: "74.8vh",
		flexShrink: 0,
		borderRadius: "16px",
		border: "1px solid #499CE9",
		background: "linear-gradient(160deg, #051524 18%, rgba(16, 73, 127, 0.37) 100%,rgba(16, 73, 127, 0.01) 100%)",
		marginTop: '-0.1vh',
		marginLeft: '-0.1vw',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
	},
	Outline: {
		width: "8vw",
		height: "8vw",
		flexShrink: 0,
		borderRadius: "104px",
		border: "1px solid #499CE9",
		background: "linear-gradient(179deg, #051524 0%, #10497f2 100%)",
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		alignContent: 'center',
	},
	AvatarStyles: {
		width: "7vw",
		height: "7vw",
		flexShrink: 0,
		borderRadius: "104px",
		background: "url(<path-to-image>), lightgray 50% / cover no-repeat",

	},
	statsContainer: {
		width: "22vw",
		height: "12vh",
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "flex-start",
	},
	statSquares: {
		width: "4vw",
		height: "8vh",
		flexShrink: 0,
		borderRadius: "16px",
		border: "1px solid #499CE9",
		background: "#171312",
		backdropFilter: "blur(5px)",
		display: "flex",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
	},
	statBox: {
		display: "flex",
		justifyContent: "center",
		flexDirection: "column",
		justifyContent: "space-between",
		alignItems: "center",
		width: "4vw",
		height: "8vh",
		flexShrink: 0,
		color: "var(--greys-blue-grey-100, #FFF)",
		fontFamily: "Quicksand",
		fontSize: "4vh",
		fontStyle: "normal",
		fontWeight: 700,
		lineHeight: "20px /* 142.857% */",
	},
	nameBox: {
		display: "flex",
		justifyContent: "center",
		flexDirection: "column",
		justifyContent: "space-between",
		marginTop: "4vh",
		marginBottom: "8vh",
		alignItems: "center",
		width: "20vw",
		height: "10vh",
		flexShrink: 0,
		color: "var(--greys-blue-grey-100, #FFF)",
		fontFamily: "Quicksand",
		fontSize: "14px",
		fontStyle: "normal",
		fontWeight: 700,
		lineHeight: "20px /* 142.857% */",
	},
	ranking: {
		width: "22vw",
		height: "5vh",
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "flex-end",
	},
}

