import theme from './ThemeStyles'

export const {
	container,
	CharacterPanel,
	AvatarStyles,
	Outline,
	statsContainer,
	statSquares,
	statBox,
	nameBox,
	ranking,
	buttonsContainer,
	buttonsContainer_sm,
	MenuPanelContainer,
} =
{
	container: {
		overflow: 'hidden',
		margin: 'auto',
		// width: "76.7vw",
		width: "100%",
		height: "100%",
		display: 'flex',
		flexDirection: 'row',
	},
	CharacterPanel: {
		width: "25vw",
		// height: "74.8vh",
		flexShrink: 0,
		borderRadius: "2vh 0vh 0vh 2vh",
		border: "0px solid #499CE9",
		borderRight: "1px solid #499CE9",
		background: "linear-gradient(160deg, #051524 18%, rgba(16, 73, 127, 0.37) 100%,rgba(16, 73, 127, 0.01) 100%)",
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'space-evenly',
	},
	Outline: {
		width: "15vw",
		height: "15vw",
		flexShrink: 0,
		borderRadius: "100%",
		border: "1px solid #499CE9",
		background: "linear-gradient(179deg, #051524 0%, #10497f2 100%)",
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		alignContent: 'center',
	},
	AvatarStyles: {
		width: "14vw",
		height: "14vw",
		flexShrink: 0,
		borderRadius: "100%",
		background: "url(<path-to-image>), lightgray 50% / cover no-repeat",

	},
	statsContainer: {
		width: "90%",
		height: "6vW",
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "flex-start",
	},
	statSquares: {
		width: "auto",
		height: "auto",
		flexShrink: 0,
		borderRadius: "26%",
		border: "1px solid #499CE9",
		background: "#171312",
		backdropFilter: "blur(5px)",
		display: "flex",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
		padding: '0.5vw 1vw',
	},
	statBox: {
		display: "flex",
		justifyContent: "center",
		flexDirection: "column",
		justifyContent: "space-between",
		alignItems: "center",
		width: "auto",
		height: "auto",
		flexShrink: 0,
		color: "var(--greys-blue-grey-100, #FFF)",
		fontFamily: "Quicksand",
		// fontSize: "4vh",
		fontStyle: "normal",
		fontWeight: 700,
		lineHeight: "20px /* 142.857% */",
	},
	nameBox: {
		display: "flex",
		justifyContent: "center",
		flexDirection: "column",
		justifyContent: "space-between",
		alignItems: "center",
		width: "20vw",
		// height: "10vh",
		flexShrink: 0,
		color: "var(--greys-blue-grey-100, #FFF)",
		fontFamily: "Quicksand",
		fontSize: "14px",
		fontStyle: "normal",
		fontWeight: 700,
		lineHeight: "20px /* 142.857% */",
	},
	ranking: {
		width: "22vw",
		height: "5vh",
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "flex-end",
	},
	buttonsContainer: {
		width: "11vw",
		height: "50vh",
		display: "flex",
		flexDirection: "column",
		justifyContent: "space-around",
		alignItems: "left",
		flexWrap: "wrap",
	},
	buttonsContainer_sm: {
		width: "11vw",
		height: "15vh",
		display: "flex",
		flexDirection: "column",
		justifyContent: "space-around",
		alignItems: "left",
		flexWrap: "wrap",
	},
	MenuPanelContainer: {
		width: "15vw",
		height: "75vh",
		display: "flex",
		flexDirection: "column",
		justifyContent: "space-around",
		alignItems: "center",
	}
}

export const { rowStyles } = {
	rowStyles: {
		background: theme.palette.background.paper,
		borderRadius: 6,
		margin: 1,
		flexDirection: 'row',
		gap: '1vw',
		padding: '2vh',
		width: '100%',
		width: '25vw',
	}
}